import { readFile } from "node:fs/promises";

const [app, html, sw, css, manifest, basicGrooves, syncGrooves, grooveImport, cleanGrooves, grooveConfig] = await Promise.all([
  readFile("app.js", "utf8"),
  readFile("index.html", "utf8"),
  readFile("service-worker.js", "utf8"),
  readFile("styles.css", "utf8"),
  readFile("manifest.webmanifest", "utf8"),
  readFile("grooves/Basic Grooves/basic-grooves.json", "utf8"),
  readFile("scripts/sync-grooves.mjs", "utf8"),
  readFile("scripts/groove-import-lib.mjs", "utf8"),
  readFile("scripts/clean-grooves.mjs", "utf8"),
  readFile(".groovesrc.json", "utf8"),
]);

const checks = [
  [html.includes('href="vendor/oat/oat.min.css"'), "Oat UI local référencé"],
  [html.includes('src="vendor/alpine/alpine.min.js"'), "Alpine local référencé"],
  [html.includes('id="theme-toggle"'), "toggle clair/sombre présent"],
  [css.includes("--bt-bg:") && css.includes("--bt-grid-width:"), "variables CSS centralisées"],
  [css.includes('#play-pause-icon:not(.fa-play):not(.fa-pause)::before'), "icône Play initiale présente"],
  [html.includes('id="practice-panel"') && html.includes('id="practice-button"'), "interface Practice présente"],
  [app.includes('class PracticeController') && app.includes('scheduleCountIn'), "Practice V1 tempo et count-in présent"],
  [app.includes('layerPlan') && app.includes('practice.snare') && app.includes('practice.kick'), "Practice V2 couches présent"],
  [app.includes('notes fantômes') && app.includes('velocityForCell'), "Practice V3 accents et notes fantômes présent"],
  [app.includes("event.shiftKey"), "Shift+clic de grille présent"],
  [app.includes("Ctrl/Cmd+Shift+clic") && app.includes("this.seq.clearCell(targetIndex)"), "Ctrl/Cmd+Shift+clic de suppression répétée présent"],
  [app.includes("drag.wholeGrid") && app.includes("translateGrid(deltaTracks, deltaSteps)"), "Alt+Shift+glisser déplace toute la grille"],
  [app.includes("createStereoPanner") && app.includes("trackPans") && css.includes(".rotary-knob"), "mix Pan/Volume rotatif présent"],
  [css.includes(".track-shift-controls") && css.includes(".pattern-shift-global"), "flèches de décalage visibles à gauche"],
  [app.includes('new StorageManager("mem")'), "mémoires URL activées"],
  [app.includes("new URLSearchParams(location.hash.slice(1))"), "lecture du hash URL présente"],
  [!app.includes('localStorage.getItem("mem")') && !app.includes('localStorage.setItem("mem")'), "localStorage retiré des mémoires"],
  [app.includes("history.replaceState"), "mise à jour du hash sans navigation"],
  [sw.includes('"./vendor/oat/oat.min.css"') && sw.includes('"./vendor/oat/oat.min.js"'), "Oat inclus dans l’app shell PWA"],
  [sw.includes('battrochtek-v43'), "cache PWA v43"],
  [css.includes('--bt-instrument-text:') && !app.includes('label.style.color'), "couleur des instruments pilotée par le thème"],
  [css.includes('.bt-tooltip') && html.includes('id="bt-tooltip"'), "tooltips adaptatifs présents"],
  [!html.includes('id="bt-help"'), "ancienne aide au survol retirée"],
  [!css.includes('.memory-saved::after'), "pastille mémoire supprimée"],
  [css.includes('margin-top: 14px') && css.includes('.transport-bar'), "espacement grille / transport présent"],
  [app.includes("SAMPLE_LIBRARY") && app.includes("setTrackSample"), "bibliothèque de samples et Kit Custom présents"],
  [app.includes("ARENA 909") && app.includes("NEON 808") && app.includes("GLITCH LAB"), "nouveaux kits distincts présents"],
  [html.includes("data-bt-tooltip=") && !html.includes(" title="), "une seule implémentation de tooltip"],
  [html.includes('id="share-button"') && html.includes('id="share-dialog"'), "dialog de partage présent"],
  [html.includes('src="vendor/qrcode/qrcode.js"') && sw.includes('"./vendor/qrcode/qrcode.js"'), "QR code local inclus dans la PWA"],
  [app.includes('shareParams.set("mem"') && app.includes('navigator.clipboard'), "lien de groove QR/copie présent"],
  [app.includes('renderCanvas(this.dom.shareQr, appUrl') && app.includes('const appUrl ='), "QR code limité à l’URL de l’application"],
  [!html.includes('id="save"') && !app.includes('this.dom.save'), "sauvegarde manuelle des mémoires retirée"],
  [app.includes('setTimeout(() => this.flush(), 260)') && app.includes('autoSaveMemory()'), "autosauvegarde mémoire et URL avec debounce"],
  [css.includes('min-width: 0;') && !css.includes('730px'), "canvas global 730 px retiré"],
  [app.includes('practice.changedStopped') && app.includes('optionChanged') && app.includes('setTraining'), "modification des réglages arrête l’entraînement"],
  [app.includes('setAttribute("aria-pressed", String(active))') && app.includes('setAttribute("aria-label", b.dataset.btTooltip)'), "états ARIA Mute/Solo et mémoires présents"],
  [app.includes('{ v: 5, s:') && app.includes('payload?.v === 4') && app.includes('payload?.v === 3') && app.includes('payload?.v === 1'), "mémoires v5 signature+BPM+grille avec migration des anciens liens"],
  [app.includes('this.store.set(this.memorySlot, this.signatureIndex, this.gridSnapshot(), this.tempo)') && app.includes('this.tempo = Math.round(Util.clamp(entry.tempo'), "mémoires limitées à grille + signature + BPM"],
  [app.includes('targetAnnounced') && !app.includes('practiceAction === "stop"'), "Practice boucle au tempo objectif"],
  [app.includes('e.code === "Space" && !mod') && app.indexOf('e.code === "Space" && !mod') < app.indexOf('if (editing || mod || e.altKey) return;'), "Espace prioritaire même dans les selects"],
  [app.includes('i % this.seq.signature.barSteps === 0'), "bar-accent sur chaque début de mesure"],
  [css.includes(".grid .cell.capo { box-shadow: inset 2px 0 0 var(--bt-accent-strong); }"), "capo utilise la même bordure que first"],
  [basicGrooves.includes('"sourceLabel": "Basic Grooves"') && html.includes('id="preset-source"'), "Basic Grooves dans ./grooves et sélecteur de source présents"],
  [html.includes('grooves/external-grooves.js'), "bundle de corpus externes chargé"],
  [sw.includes('./grooves/external-grooves.js'), "corpus externes inclus dans la PWA"],
  [app.includes('TRACK_COUNT: 9') && app.includes('tomFloor:7') && app.includes('kick:8'), "grille GMD étendue à 9 pistes"],
  [app.includes('addSelectedPatch()') && app.includes('const available = CONFIG.MEMORY_SLOTS - startSlot') && app.includes('selected.entries.slice(0, available)'), "import du patch tronqué à partir de la mémoire active"],
  [app.includes('const previousSlots = this.seq.store.populated().filter(slot => slot < startSlot)') && app.includes('entry.pattern, inheritedTempo'), "groove importé hérite du BPM de la dernière mémoire précédente"],
  [html.includes('id="groove-search"'), "recherche globale de grooves présente"],
  [html.includes('class="groove-search-results"') && !html.includes('<datalist id="groove-search-list"'), "autocomplete global sous la recherche sans datalist natif"],
  [html.includes('id="groove-preview"') && app.includes('toggleGroovePreview()') && app.includes('previewLoop()'), "préécoute casque non destructive présente"],
  [html.includes('id="groove-add"') && app.includes('addSelectedPatch()'), "bouton + d’ajout du patch présent"],
  [!html.includes('id="groove-refresh"') && !app.includes('reloadSelectedPresetMemory()'), "rechargement de groove retiré"],
  [!app.includes('this.dom.presetGroove.addEventListener("change", () => this.loadSelectedPreset())') && app.includes('if (this.previewEnabled) this.restartGroovePreview()'), "sélection d’un groove non destructive"],
  [app.includes('buildGlobalSearch()') && app.includes('ArrowDown') && app.includes('ArrowUp'), "autocomplete global clavier présent"],
  [syncGrooves.includes('importGrooveRoot("grooves")'), "sync utilise ./grooves en minuscules"],
  [cleanGrooves.includes('importGrooveRoot("grooves")') && !cleanGrooves.includes('importGrooveRoot("Grooves")'), "cleaner utilise ./grooves en minuscules"],
  [JSON.parse(grooveConfig).minimumDifference === 10, "différence minimale configurée à 10%"],
  [grooveImport.includes("for (const name of await readdir(root))") && grooveImport.includes("label:name"), "nom de Source issu du dossier de premier niveau"],
  [!html.includes('id="tempo-ramp"') && !app.includes('tempoRampEnabled'), "ancien escalier BPM retiré"],
  [!html.includes('practice-metronome') && !app.includes('metronomeDuringPractice'), "métronome Practice retiré"],
  [html.includes('id="language-select"') && app.includes('I18N_RESOURCES') && app.includes('i18next'), "traductions FR/EN/ES avec i18next"],
  [css.includes('.memory-selected') && css.includes('#f0b841'), "mémoire active en jaune first bar"],
  [css.includes('.practice-played') && app.includes('applyPracticeTrackHighlight'), "surbrillance légère des pistes Practice"],
  [manifest.includes('icons/icon-512.png'), "icônes PWA déclarées"],
  [html.includes('id="grid-shift-up"') && html.includes('id="grid-shift-down"') && app.includes('shiftGridTracks'), "flèches haut/bas de déplacement global présentes"],
  [app.includes('if (this.previewEnabled) this.stopGroovePreview({ silent:true });') && app.includes('if (this.scheduler?.playing) this.scheduler.stop();'), "Play et préécoute sont mutuellement exclusifs"],
  [css.includes('.groove-preview[aria-pressed="true"]') && css.includes('background: var(--bt-accent)'), "préécoute possède un état actif visible"],
];

const failed = checks.filter(([ok]) => !ok);
for (const [ok, label] of checks) console.log(`${ok ? "✓" : "✗"} ${label}`);
if (failed.length) {
  console.error(`\n✗ ${failed.length} contrôle${failed.length > 1 ? "s" : ""} en échec :`);
  for (const [, label] of failed) console.error(`  - ${label}`);
  process.exit(1);
}
