import { readFile } from "node:fs/promises";

const [app, html, sw, css, manifest, sampleManifest, externalGrooves, syncGrooves, grooveImport, cleanGrooves, grooveConfig] = await Promise.all([
  readFile("app.js", "utf8"),
  readFile("index.html", "utf8"),
  readFile("service-worker.js", "utf8"),
  readFile("styles.css", "utf8"),
  readFile("manifest.webmanifest", "utf8"),
  readFile("samples/manifest-v2.js", "utf8"),
  readFile("grooves/external-grooves.js", "utf8"),
  readFile("scripts/sync-grooves.mjs", "utf8"),
  readFile("scripts/groove-import-lib.mjs", "utf8"),
  readFile("scripts/clean-grooves.mjs", "utf8"),
  readFile(".groovesrc.json", "utf8"),
]);

const diversity = JSON.parse(await readFile("musicology/diversity-report.json", "utf8"));

const checks = [
  [html.includes('href="vendor/oat/oat.min.css"'), "Oat UI local référencé"],
  [html.includes('src="vendor/alpine/alpine.min.js"'), "Alpine local référencé"],
  [html.includes('id="theme-toggle"'), "toggle clair/sombre présent"],
  [css.includes("--bt-bg:") && css.includes("--bt-grid-width:"), "variables CSS centralisées"],
  [css.includes('#play-pause-icon:not(.fa-play):not(.fa-pause)::before'), "icône Play initiale présente"],
  [html.includes('id="practice-panel"') && html.includes('id="practice-button"'), "interface Practice présente"],
  [app.includes('class PracticeController') && app.includes('scheduleCountIn'), "Practice V1 tempo et count-in présent"],
  [app.includes('layerPlan') && app.includes('practice.snare') && app.includes('practice.kick'), "Practice V2 couches présent"],
  [app.includes('notes fantômes') && app.includes('velocityForCell'), "Practice V3 accents et notes fantômes présent"],
  [app.includes("event.shiftKey"), "Shift+clic de grille présent"],
  [app.includes("Ctrl/Cmd+Shift+clic") && app.includes("this.seq.clearCell(targetIndex)"), "Ctrl/Cmd+Shift+clic de suppression répétée présent"],
  [app.includes("moveSelection(deltaTracks, deltaSteps") && app.includes("selectedCells = new Set"), "sélection multi-note déplaçable sur les 2 axes"],
  [app.includes("createStereoPanner") && app.includes("trackPans") && css.includes(".rotary-knob"), "mix Pan/Volume rotatif présent"],
  [css.includes(".track-shift-controls") && css.includes(".pattern-shift-global"), "flèches de décalage visibles à gauche"],
  [app.includes('new StorageManager("mem")'), "mémoires URL activées"],
  [app.includes("new URLSearchParams(location.hash.slice(1))"), "lecture du hash URL présente"],
  [!app.includes('localStorage.getItem("mem")') && !app.includes('localStorage.setItem("mem")'), "localStorage retiré des mémoires"],
  [app.includes("history.replaceState"), "mise à jour du hash sans navigation"],
  [app.includes("isApplyingUrlState") && app.includes("BattrochtekUrlSync?.isApplying") && app.includes("urlApplyCount"), "garde anti-boucle URL params ↔ état app présent"],
  [app.includes("reloadFromUrl()") && app.includes("hashchange") && app.includes("popstate") && app.includes("applyUrlState") && app.includes("lastAppliedHash"), "navigation favoris/historique recharge le groove URL sans reload"],
  [sw.includes('"./vendor/oat/oat.min.css"') && sw.includes('"./vendor/oat/oat.min.js"'), "Oat inclus dans l’app shell PWA"],
  [sw.includes('battrochtek-v120') && sw.includes('battrochtek-audio-v7'), "caches PWA/audio v120/v7"],
  [html.includes('id="fullscreen-toggle"') && app.includes('setupFullscreen()') && app.includes('key==="x"'), 'plein écran bouton + raccourci Shift+X présent'],
  [app.includes('bell:1') && app.includes('ride:2') && !html.includes('value="bell"') && !html.includes('value="crash"') && html.includes('value="hihat"') && html.includes('value="ride"') && app.includes('bt_detroit_ride_bell'), 'piste Bell présente + Main droite simplifiée Charley/Ride'],
  [!css.slice(css.indexOf('.feel-influence-block{'), css.indexOf('}',css.indexOf('.feel-influence-block{'))).includes('border-top'), 'Influence FEEL sans border-top'],
  [css.includes('--bt-instrument-text:') && !app.includes('label.style.color'), "couleur des instruments pilotée par le thème"],
  [css.includes('.bt-tooltip') && html.includes('id="bt-tooltip"'), "tooltips adaptatifs présents"],
  [!html.includes('id="bt-help"'), "ancienne aide au survol retirée"],
  [!css.includes('.memory-saved::after'), "pastille mémoire supprimée"],
  [css.includes('.grid-shift-under-grid') && css.includes('padding-bottom: 12px'), "espacement grille / transport présent"],
  [app.includes("SAMPLE_LIBRARY") && app.includes("setTrackSample"), "bibliothèque de samples et Kit Custom présents"],
  [app.includes("class SampleResolver") && app.includes("SAMPLE_MANIFEST_VERSION: 2"), "Sample Manifest v2 et resolver présents"],
  [app.includes("this.activeChokes = new Map()") && app.includes("linearRampToValueAtTime(0"), "choke groups audio présents"],
  [app.includes("Round-robin follows the resolved articulation/layer"), "round-robin suit l’articulation résolue"],
  [sampleManifest.includes("WORLD PERCUSSION") && sampleManifest.includes("world_darbuka") && sampleManifest.includes("world_frame_large"), "pack World acoustique VCSL présent"],
  [sampleManifest.includes("ANALOG CLASSIC") && sampleManifest.includes("DETROIT HYBRID") && sampleManifest.includes("DIGITAL 80"), "packs électroniques CC0 présents"],
  [app.includes("performanceArticulation") && app.includes("articulation = this.ui?.feel?.performanceArticulation"), "FEEL transmet les articulations au moteur audio"],
  [html.includes('samples/manifest-v2.js') && sw.includes('./samples/manifest-v2.js'), "manifeste samples chargé et disponible hors ligne"],
  [html.includes('id="monitoring-toggle"') && app.includes("monitoringEnabled"), "monitoring cellule/sample présent"],
  [html.includes('id="record-toggle"') && app.includes("quantizedRecordStep") && app.includes("triggerKeyboardPad"), "Record clavier quantifié sans retarder le preview présent"],
  [html.includes('data-velocity-level="1"') && html.includes('data-velocity-level="5"') && app.includes("currentVelocityLevel = 3"), "palette vélocité 1→5 avec niveau 3 par défaut présente"],
  [app.includes("applyVelocityToSelection") && app.includes("this.selectAllNotes()"), "palette appliquée à la sélection + Ctrl/Cmd+A présents"],
  [app.includes("this.invertSelection()") && app.includes('key === "i"'), "Ctrl/Cmd+I inverse la sélection"],
  [app.includes("/^Digit[1-5]$/") && html.includes("data-velocity-level=\"5\""), "touches 1→5 sélectionnent la vélocité"],
  [html.includes("Décaler la sélection à gauche") && !html.includes("Décaler toute la grille à gauche"), "tooltips des flèches décrivent la sélection"],
  [app.includes("selectTrackNotes") && app.includes("track-row-select") && !app.includes("shiftLeft.addEventListener"), "sélection de ligne remplace les déplacements par ligne"],
  [html.includes('id="memory-duplicate"') && app.includes("reorderMemorySlots") && css.includes("memory-drop-before"), "duplication + drag/drop des mémoires présents"],
  [css.includes("outline:2px solid #ffd400"), "sélection de grille jaune présente"],
  [app.includes("adjustSelectionVelocity") && html.includes('id="velocity-decrease"') && html.includes('id="velocity-increase"'), "vélocité +/- appliquée à la sélection présente"],
  [app.includes("SAMPLE_VISIBLE_CHOICES") && app.includes("sample-browser-dialog"), "sélecteur sample recherchable et RR masqués"],
  [html.includes('class="bt-version"') && html.includes('fa-github'), "version + GitHub présents dans le header"],
  [html.includes('class="sequencer-card-header"') && html.indexOf('id="master-level"') > html.indexOf('sequencer-card-header'), "Master + VU déplacés dans le header du séquenceur"],
  [app.includes("sample-browser-filter-chips") && app.includes("filterMatches") && app.includes("setFilter"), "navigateur de sons avec filtres métadonnées"],
  [app.includes("pointerenter',()=>{ button.classList.add('hover-preview'); previewSample(sample); }") && app.includes("button.addEventListener('click',()=>activate"), "hover écoute sans sélectionner, clic sélectionne"],
  [app.includes("PAD_KEYBOARD_MAP") && app.includes("BracketLeft:0"), "pads clavier AZERTY/QWERTY présents"],
  [app.includes("grid-selection-box") && app.includes('kind:"marquee"') && app.includes('kind:"move"'), "édition DAW : rectangle de sélection + drag de sélection"],
  [app.includes("JAZZ CLUB") && app.includes("VINTAGE ROCK") && app.includes("DETROIT HYBRID") && app.includes("GLITCH LAB"), "kits acoustiques/électro curatés présents"],
  [html.includes("data-bt-tooltip=") && !html.includes(" title="), "une seule implémentation de tooltip"],
  [html.includes('id="share-button"') && html.includes('id="share-dialog"'), "dialog de partage présent"],
  [html.includes('src="vendor/qrcode/qrcode.js"') && sw.includes('"./vendor/qrcode/qrcode.js"'), "QR code local inclus dans la PWA"],
  [app.includes('shareParams.set("mem"') && app.includes('navigator.clipboard'), "lien de groove QR/copie présent"],
  [app.includes('shareParams.set("snd"') && app.includes("compactSoundState") && app.includes("restoreSoundState"), "URL partage kit + Custom + mix + Swing présent"],
  [app.includes('renderCanvas(this.dom.shareQr, appUrl') && app.includes('const appUrl ='), "QR code limité à l’URL de l’application"],
  [!html.includes('id="save"') && !app.includes('this.dom.save'), "sauvegarde manuelle des mémoires retirée"],
  [app.includes('setTimeout(() => this.flush(), 260)') && app.includes('autoSaveMemory()'), "autosauvegarde mémoire et URL avec debounce"],
  [css.includes('min-width: 0;') && !css.includes('730px'), "canvas global 730 px retiré"],
  [app.includes('practice.changedStopped') && app.includes('optionChanged') && app.includes('setTraining'), "modification des réglages arrête l’entraînement"],
  [app.includes('setAttribute("aria-pressed", String(active))') && app.includes('setAttribute("aria-label", b.dataset.btTooltip)'), "états ARIA Mute/Solo et mémoires présents"],
  [(app.includes('{ v: 7, s:') || app.includes('{ v:7, s:')) && app.includes('payload?.v === 6') && app.includes('payload?.v === 5') && app.includes('payload?.v === 4') && app.includes('payload?.v === 3') && app.includes('payload?.v === 1'), "mémoires v7 signature+BPM+grille+FEEL + migration v6 neuf pistes"],
  [app.includes('this.store.set(this.memorySlot, this.signatureIndex, this.gridSnapshot(), this.tempo)') && app.includes('this.tempo = Math.round(Util.clamp(entry.tempo'), "CORE mémoire limité à grille + signature + BPM, FEEL séparé"],
  [app.includes('targetAnnounced') && !app.includes('practiceAction === "stop"'), "Practice boucle au tempo objectif"],
  [app.includes('e.code === "Space" && !mod') && app.indexOf('e.code === "Space" && !mod') < app.indexOf('if (editing || mod || e.altKey) return;'), "Espace prioritaire même dans les selects"],
  [app.includes('i % this.seq.signature.barSteps === 0'), "bar-accent sur chaque début de mesure"],
  [css.includes(".grid .cell.capo { box-shadow: inset 2px 0 0 var(--bt-accent-strong); }"), "capo utilise la même bordure que first"],
  [externalGrooves.includes('Battrochtek Curated') && externalGrooves.includes('canonicalId') && !html.includes('id="preset-source"') && html.includes('id="preset-family"'), "bibliothèque Curated unique sans sélecteur de source"],
  [html.includes('grooves/external-grooves.js'), "bundle de corpus externes chargé"],
  [sw.includes('./grooves/external-grooves.js'), "corpus externes inclus dans la PWA"],
  [app.includes('TRACK_COUNT: 10') && app.includes('bell:1') && app.includes('tomFloor:8') && app.includes('kick:9'), "grille étendue à 10 pistes avec Bell"],
  [app.includes('addSelectedPatch()') && app.includes('const available = CONFIG.MEMORY_SLOTS - startSlot') && app.includes('selected.entries.slice(0, available)'), "ajout du patch tronqué à partir de la mémoire active"],
  [app.includes('const feelWasEnabled = this.feel.enabled') && app.includes('const autoWasEnabled = this.feel.auto') && !app.includes('this.setFeelEnabled(true, { applyNow:true, save:true })'), "ajouter groove préserve FEEL et AUTO"],
  [app.includes('if(next===this.feel.enabled)') && app.includes('saveFeelStateToMemory'), "setFeelEnabled idempotent + état FEEL mémorisé"],
  [app.includes('const core=this.feel.enabled ? this.feel.cores.get(this.seq.memorySlot) : null') && app.includes('this.saveFeelStateToMemory()'), "mémoire sauvegarde CORE + paramètres FEEL séparément"],
  [app.includes('this.feel.captureCore({inferLayers:true});') && app.includes('this.feel.rightHandMode=this.feel.detectPrimaryRightHand();') && app.includes('this.feel.enabled=true; this.feel.auto=true;'), "activation FEEL repart du CORE courant"],
  [app.includes('const previousSlots = this.seq.store.populated().filter(slot => slot < startSlot)') && app.includes('entry.pattern, inheritedTempo'), "groove ajouté hérite du BPM de la dernière mémoire précédente"],
  [html.includes('id="groove-search"'), "recherche globale de grooves présente"],
  [html.includes('class="groove-search-results"') && !html.includes('<datalist id="groove-search-list"'), "autocomplete global sous la recherche sans datalist natif"],
  [html.includes('id="groove-preview"') && app.includes('toggleGroovePreview()') && app.includes('previewLoop()'), "préécoute casque non destructive présente"],
  [html.includes('id="groove-add"') && app.includes('addSelectedPatch()'), "bouton + d’ajout du patch présent"],
  [!html.includes('id="groove-refresh"') && !app.includes('reloadSelectedPresetMemory()'), "rechargement de groove retiré"],
  [!app.includes('this.dom.presetGroove.addEventListener("change", () => this.loadSelectedPreset())') && app.includes('if (this.previewEnabled) this.restartGroovePreview()'), "sélection d’un groove non destructive"],
  [app.includes('buildGlobalSearch()') && app.includes('ArrowDown') && app.includes('ArrowUp'), "autocomplete global clavier présent"],
  [syncGrooves.includes('importGrooveRoot("grooves")'), "sync utilise ./grooves en minuscules"],
  [cleanGrooves.includes('importGrooveRoot("grooves")') && !cleanGrooves.includes('importGrooveRoot("Grooves")'), "cleaner utilise ./grooves en minuscules"],
  [JSON.parse(grooveConfig).minimumDifference === 10, "différence minimale configurée à 10%"],
  [grooveImport.includes("for (const name of await readdir(root))") && grooveImport.includes("label:name"), "nom de Source issu du dossier de premier niveau"],
  [!html.includes('id="tempo-ramp"') && !app.includes('tempoRampEnabled'), "ancien escalier BPM retiré"],
  [!html.includes('practice-metronome') && !app.includes('metronomeDuringPractice'), "métronome Practice retiré"],
  [html.includes('id="language-select"') && app.includes('I18N_RESOURCES') && app.includes('i18next'), "traductions FR/EN/ES avec i18next"],
  [css.includes('.memory-selected') && css.includes('#f0b841'), "mémoire active en jaune first bar"],
  [css.includes('.practice-played') && app.includes('applyPracticeTrackHighlight'), "surbrillance légère des pistes Practice"],
  [manifest.includes('icons/icon-512.png'), "icônes PWA déclarées"],
  [html.includes('id="grid-shift-up"') && html.includes('id="grid-shift-down"') && app.includes('shiftGridTracks'), "flèches haut/bas de déplacement global présentes"],
  [app.includes('if (this.previewEnabled) this.stopGroovePreview({ silent:true });') && app.includes('if (this.scheduler?.playing) this.scheduler.stop();'), "Play et préécoute sont mutuellement exclusifs"],
  [css.includes('.groove-preview[aria-pressed="true"]') && css.includes('background: var(--bt-accent)'), "préécoute possède un état actif visible"],
  [html.includes('id="feel-xy"') && html.includes('id="feel-groove-xy"') && html.includes('id="feel-enabled"') && !html.includes('id="feel-auto"'), "FEEL deux pads + switch, AUTO visible retiré"],
  [!html.includes('id="feel-orchestration-auto"') && !html.includes('id="feel-orchestration-every"'), "AUTO Orchestration visible retiré"],
  [html.includes('value="minimal"') && html.includes('value="standard"') && html.includes('value="busy"') && html.includes('value="wild"'), "presets FEEL Minimal/Pocket/Standard/Busy/Wild présents"],
  [app.includes('applyMacroPreset(name)') && app.includes('macroProfile'), "Orchestration pilote un macro-preset FEEL"],
  [app.includes('this.autoOrchestration=false') && app.includes('this.autoOrchestrationEvery="auto"'), "ancien AUTO Orchestration neutralisé"],
  [app.includes('minimal:{ orchestrationMode:"pocket"') && app.includes('wild:{ orchestrationMode:"fullkit"'), "macros FEEL règlent influences et orchestration"],
  [app.includes('closeFeelForMemoryChange()') && app.includes('this.ui.closeFeelForMemoryChange?.();'), "changement de mémoire conserve/restaure son état FEEL"],
  [app.includes('class FeelController') && app.includes('randomFor(key)'), "FEEL déterministe par seed présent"],
  [app.includes('baseActive.has(track*steps+st) && (track===R.snare||track===R.kick)') && app.includes('The complete source groove is always copied first'), "CORE kick/snare verrouillé présent"],
  [app.includes('sourceLimbAssignments()') && !html.includes('feel-limb-summary'), "FEEL identifie les membres en interne sans exposer la plomberie"],
  [app.includes('The complete source groove is always copied first') && app.includes('for(const i of baseActive){ active.add(i); copyVelocity(i); }'), "FEEL conserve intégralement le groove source avant tout agrément"],
  [app.includes('Preserve the source hi-hat skeleton') && app.includes('hh-open:') && app.includes('hh-orn:') && app.includes('maxAdds'), "charley source protégé : articulation + ornements locaux plafonnés"],
  [html.includes('id="feel-advanced"') && html.includes('data-feel-influence="rightHand"') && html.includes('data-feel-influence="toms"') && html.includes('data-feel-influence="crash"'), "Influence FEEL inclut variante Main droite + Toms + Crash"],
  [html.includes('<option value="hihat"') && html.includes('<option value="ride"') && !html.includes('<option value="auto"') && !html.includes('<option value="bell"') && !html.includes('<option value="crash"') && !html.includes('<option value="perc"'), "Main droite UI limitée à Charley/Ride"],
  [app.includes('feel.influenceOpenHat') && app.includes('feel.influenceBell') && app.includes('variant=this.influenceScale("rightHand")'), "Influence contextuelle Open HH / Bell présente"],
  [app.includes('crashInfluence=this.influenceScale("crash")') && app.includes('this.influenceLevel("crash")>0'), "Crash possède une influence indépendante"],
  [html.indexOf('id="live-break"') < html.indexOf('id="live-variation"') && html.indexOf('id="live-variation"') < html.indexOf('id="feel-randomize"') && html.indexOf('id="feel-randomize"') < html.indexOf('id="feel-reset"'), "Actions FEEL ordonnées Break / Var / Dé / Reset"],
  [html.includes('id="feel-randomize"') && app.includes('randomizeParameters()'), "Dé FEEL randomise les paramètres sans toucher au CORE"],
  [app.includes('returnFillProfile(style=this.style())') && app.includes('tomBias:.92') && app.includes('crash:.96'), "fills de reprise adaptés par famille de style"],
  [app.includes('const toms=force || this.influenceLevel("toms")>0') && app.includes('tomInfluence=this.influenceScale("toms")'), "Toms = 0 bloque le FEEL normal mais pas le fill Live de reprise"],
  [app.includes('const wantsCrash=force || (this.influenceLevel("crash")>0') && app.includes('add(R.crash,0'), "Crash de reprise Live autorisé même si Influence Crash = 0"],
  [html.includes('class="shortcut-help-outside"') && html.indexOf('class="shortcut-help-outside"') > html.indexOf('<div class="bt">'), "Raccourcis clavier sortis du bloc .bt"],
  [app.includes('fullscreenTarget=document.querySelector(".bt")') && app.includes('fullscreenTarget?.requestFullscreen()'), "plein écran limité au bloc .bt"],
  [html.includes('PRÉSERVER') && app.includes('this.feel.deviation = Math.round') && html.includes('id="feel-groove-xy"'), "FEEL deux pads Transformation/Density + Swing/Energy présents"],
  [app.includes('humanize({ active, accent, soft, strong, ghost') && app.includes('played.length<=2'), "Human Drummer Engine limite les frappes de mains simultanées"],
  [app.includes('Open/closed hi-hat are articulations of one instrument') && app.includes('drop(R.closedHat,step)') && app.includes('drop(R.openHat,step)'), "Human Drummer Engine rend hi-hat open/closed exclusifs"],
  [app.includes('fillSteps.has(step)') && app.includes('fillHands.length>=1'), "Human Drummer Engine libère les mains pendant les fills"],
  [app.includes('groove CORE restauré') && app.includes('if (!this.feel.enabled) return;') && app.includes('this.feel.auto=true'), "FEEL OFF restaure le CORE, AUTO interne permanent"],
  [app.includes('addGhostPhrases') && app.includes("add(R.snare,st,'ghost')") && app.includes("add(R.kick,st,'ghost')"), "ghost phrases kick/snare présentes"],
  [app.includes('addFillPhrase') && app.includes("phraseType") && app.includes('pendingResolutions'), "fills phrasés et résolution inter-boucle présents"],
  [app.includes('previousPerformances') && app.includes('continuity:'), "AUTO conserve une continuité de performance"],
  [app.includes('performanceTimingOffset') && app.includes('performanceGainScale'), "microtiming et vélocité humanisés présents"],
  [html.includes('id="feel-style"') && app.includes('orchestrationMode'), "sélecteur ORCHESTRATION présent"],
  [app.includes('applyMacroPreset(profile)') && app.includes('this.feel.applyMacroPreset(profile)'), "Orchestration change réellement les paramètres FEEL"],
  [app.includes('if(f<=0&&!force)return false') && app.includes('force?Math.max(.82,Math.pow(f,1.25))') && app.includes('ENERGY is bipolar around 50%'), "Deviation 0 interdit les fills automatiques, Live Fill reste forcable"],
  [app.includes('ENERGY is bipolar around 50%') && app.includes('const calm=(.5-e)/.5') && app.includes('const drive=(e-.5)/.5'), "Energy atténue ou renforce les accents autour de 50%"],
  [html.includes('data-i18n="feel.energy"') && !html.includes('<span>INTIME</span>'), "axe Energy simplifié et traduit"],
  [app.includes('leftFootHatPattern') && app.includes('performanceLeftFootSteps') && app.includes('!isLeftFootHat(track)'), "pied gauche HH séparé du budget des deux mains"],
  [app.includes('sourceTimeVoice()') && app.includes('return this.rightHandMode==="ride" ? "ride" : "hihat"'), "Main droite explicite Charley/Ride sans AUTO"],
  [Array.isArray(diversity.exactStructuralClusters) && diversity.exactStructuralClusters.length===0, "aucune collision structurelle exacte dans les 213 archétypes"],
  [diversity.nearDuplicateSummary?.unresolved===0, "paires proches musicologiquement arbitrées"],
  [app.includes('this.coreMode = "locked"') && app.includes('this.influence = { kick:1, snare:1, rightHand:2, ghosts:2, toms:1, crash:1 }'), 'FEEL core protection + influences v59'],
  [!html.includes('id="live-fill"') && html.includes('data-feel-influence="kick"') && html.includes('class="feel-influence-block"'), 'FEEL sans bouton Fill + influence visible UI'],
  [!app.includes('key==="f"') && app.includes('key==="x"') && app.includes('beginLiveBreakGesture') && app.includes('triggerLiveAction("live.fill")'), 'Fill clavier F supprimé, Break conserve son fill interne'],
  [!html.includes('value="perc"') && app.includes('tomInfluence=this.influenceScale("toms")') && html.includes('data-feel-influence="crash"'), 'Main droite ne duplique plus Toms ; Crash/Toms sont des influences'],
  [app.includes('rewriteBase=[0,.025,.095,.19]') && app.includes('core-rewrite:'), 'CORE FREE peut réellement réécrire kick/snare selon Deviation'],
  [app.includes('press:id=>ui.pressAction(id)') && app.includes('release:id=>ui.releaseAction(id)'), 'action bus prêt pour footswitch/MIDI Learn'],

  [html.includes('id="feel-set-core"') && app.includes('setDisplayedGridAsFeelCore()') && css.includes('.feel-action-separator'), "bouton disquette FEEL remplace explicitement le CORE"],
  [app.includes('scheduleRightHandDetectionFromGrid()') && app.includes('rightHandDetectTimer') && app.includes('detectPrimaryRightHandFromGrid'), "Main droite pré-évaluée avec debounce quand FEEL est OFF"],
  [app.includes('if(!this.feel.enabled && action!=="live.nextMemory") return false') && app.includes('button.disabled=!feelLiveEnabled'), "Break/Variation ne peuvent plus activer FEEL et sont désactivés quand FEEL est OFF"],
  [app.includes('key==="b"){ if(!this.feel.enabled)return') && app.includes('key==="v"){ if(!this.feel.enabled)return') && app.includes('key==="h"){ if(!this.feel.enabled)return'), "raccourcis FEEL neutralisés quand FEEL est OFF"],


  [!html.includes('id="preset-source"') && !html.includes('source-selector'), "sélecteur Source retiré de l’UI"],
  [html.includes('id="memory-prev"') && html.includes('id="chain"') && html.includes('id="memory-next"') && !html.includes('id="random"') && html.includes('class="feel-panel feel-accordion"'), "FEEL devient un accordéon sous les mémoires"],
  [html.includes('id="feel-enabled"') && html.includes('id="feel-reset"') && !html.includes('id="feel-view-toggle"'), "FEEL switch + reset, pads uniquement"],
  [html.includes('<details id="feel-panel"') && html.includes('<details class="shortcut-help"') && css.includes('.feel-panel,\n.shortcut-help'), "accordéons FEEL/Aide pleine largeur"],
  [html.includes('id="feel-groove-xy"') && !html.includes('id="feel-swing"'), "Swing intégré au pad FEEL sans slider doublon"],
  [app.includes('entry.feel || null') && app.includes('payload?.v === 6'), "paramètres FEEL inclus dans les mémoires URL"],
];

const failed = checks.filter(([ok]) => !ok);
for (const [ok, label] of checks) console.log(`${ok ? "✓" : "✗"} ${label}`);
if (failed.length) {
  console.error(`\n✗ ${failed.length} contrôle${failed.length > 1 ? "s" : ""} en échec :`);
  for (const [, label] of failed) console.error(`  - ${label}`);
  process.exit(1);
}
